# Generated by Django 2.2.7 on 2020-02-25 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KeyWords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_name', models.CharField(default='', max_length=12, verbose_name='关键字')),
                ('key_type', models.CharField(choices=[('brand', '品牌'), ('specifications', '规格'), ('function', '功能'), ('texture', '材质'), ('price', '价格')], default='brand', max_length=12)),
            ],
            options={
                'verbose_name_plural': '关键字',
                'verbose_name': '关键字',
            },
        ),
    ]
