# Generated by Django 2.2.7 on 2020-02-25 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='keywords',
            options={'verbose_name': '商品关键字', 'verbose_name_plural': '商品关键字'},
        ),
        migrations.AlterField(
            model_name='keywords',
            name='key_name',
            field=models.CharField(default='', max_length=32, verbose_name='关键字'),
        ),
    ]
