# Generated by Django 2.2.7 on 2020-02-25 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_auto_20200225_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keywords',
            name='key_type',
            field=models.CharField(choices=[('brand', '品牌'), ('specifications', '规格'), ('function', '功能'), ('texture', '材质'), ('price', '价格')], default='brand', max_length=12, verbose_name='类型'),
        ),
    ]
