# Generated by Django 2.2.7 on 2020-02-25 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0006_hotsell_goods_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotsell',
            name='goods_nun',
            field=models.IntegerField(default=1, max_length=4, verbose_name='排行序号'),
        ),
    ]
