# Generated by Django 2.2.7 on 2020-02-25 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0007_hotsell_goods_nun'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotsell',
            name='goods_file',
            field=models.ImageField(default='image/atom.png', null=True, upload_to='image/%Y/%m', verbose_name='商品图片'),
        ),
        migrations.AlterField(
            model_name='hotsell',
            name='goods_nun',
            field=models.IntegerField(default=1, max_length=4, verbose_name='排行榜'),
        ),
    ]
