# Generated by Django 2.2.7 on 2020-02-25 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0008_auto_20200225_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotsell',
            name='goods_file',
            field=models.ImageField(blank=True, default='image/atom.png', null=True, upload_to='image/%Y/%m', verbose_name='商品图片'),
        ),
    ]
