# Generated by Django 2.2.7 on 2020-02-25 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0010_auto_20200225_2025'),
    ]

    operations = [
        migrations.CreateModel(
            name='NurseGoods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_id', models.IntegerField(max_length=12, verbose_name='商品详情ID')),
            ],
        ),
        migrations.AlterField(
            model_name='hotsell',
            name='goods_id',
            field=models.IntegerField(verbose_name='商品详情ID'),
        ),
        migrations.AlterField(
            model_name='hotsell',
            name='goods_nun',
            field=models.IntegerField(default=1, verbose_name='排行榜'),
        ),
    ]
