# Generated by Django 2.2.7 on 2020-02-25 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0011_auto_20200225_2027'),
    ]

    operations = [
        migrations.DeleteModel(
            name='KeyWords',
        ),
        migrations.AlterModelOptions(
            name='nursegoods',
            options={'verbose_name': '护理用品', 'verbose_name_plural': '护理用品'},
        ),
        migrations.AddField(
            model_name='nursegoods',
            name='goods_brand',
            field=models.CharField(choices=[('AEK', '爱尔康'), ('KB', '库博'), ('HC', '海昌'), ('SK', '视康'), ('CS', '蔡司'), ('MNK', '美尼康'), ('QT', '其他')], default='QT', max_length=32, verbose_name='商品品牌'),
        ),
        migrations.AddField(
            model_name='nursegoods',
            name='goods_func',
            field=models.CharField(choices=[('HLY', '护理液'), ('BLH', '伴侣盒'), ('RYY', '润眼液'), ('QXQ', '清洗器'), ('QDQ', '取戴器'), ('SLH', '双联盒')], default='HLY', max_length=32, verbose_name='商品功能'),
        ),
        migrations.AddField(
            model_name='nursegoods',
            name='goods_img',
            field=models.ImageField(blank=True, default='image/atom.png', null=True, upload_to='image/%Y/%m', verbose_name='商品图片'),
        ),
        migrations.AddField(
            model_name='nursegoods',
            name='goods_name',
            field=models.CharField(default='', max_length=200, verbose_name='商品名称'),
        ),
        migrations.AddField(
            model_name='nursegoods',
            name='goods_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='商品价格'),
        ),
        migrations.AddField(
            model_name='nursegoods',
            name='goods_sales',
            field=models.IntegerField(default=0, verbose_name='商品销量'),
        ),
        migrations.AddField(
            model_name='nursegoods',
            name='goods_spec',
            field=models.CharField(choices=[('CX', '促销装'), ('DP', '大瓶装'), ('ZP', '中瓶装'), ('XP', '小瓶装')], default='CX', max_length=32, verbose_name='商品规格'),
        ),
        migrations.AddField(
            model_name='nursegoods',
            name='goods_texture',
            field=models.CharField(choices=[('GJ', '硅胶'), ('NL', '尼龙'), ('QT', '其他')], default='QT', max_length=32, verbose_name='商品材质'),
        ),
        migrations.AddField(
            model_name='nursegoods',
            name='goods_tip',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2, verbose_name='商品评分'),
        ),
        migrations.AlterField(
            model_name='hotsell',
            name='goods_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='商品价格'),
        ),
        migrations.AlterField(
            model_name='nursegoods',
            name='goods_id',
            field=models.IntegerField(verbose_name='商品详情ID'),
        ),
    ]
