# Generated by Django 2.2.7 on 2020-02-26 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0012_auto_20200225_2110'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_name', models.CharField(default='', max_length=32, verbose_name='品牌名')),
            ],
        ),
        migrations.RemoveField(
            model_name='nursegoods',
            name='goods_func',
        ),
        migrations.RemoveField(
            model_name='nursegoods',
            name='goods_spec',
        ),
        migrations.RemoveField(
            model_name='nursegoods',
            name='goods_texture',
        ),
        migrations.AlterField(
            model_name='nursegoods',
            name='goods_brand',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.SET_DEFAULT, to='goods.Brand'),
        ),
    ]
