# Generated by Django 2.2.7 on 2020-02-26 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0014_auto_20200226_1558'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'verbose_name': '商品品牌', 'verbose_name_plural': '商品品牌'},
        ),
        migrations.AlterField(
            model_name='brand',
            name='key_name',
            field=models.CharField(default='', max_length=32, verbose_name='品牌名称'),
        ),
        migrations.AlterField(
            model_name='nursegoods',
            name='goods_brand',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='goods.Brand'),
        ),
    ]
