# Generated by Django 2.2.7 on 2020-02-26 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0015_auto_20200226_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nursegoods',
            name='goods_brand',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='goods.Brand'),
        ),
    ]
