# Generated by Django 2.2.7 on 2020-02-26 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0016_auto_20200226_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nursegoods',
            name='goods_brand',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='goods.Brand'),
        ),
    ]
