# Generated by Django 2.2.7 on 2020-02-26 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0019_auto_20200226_1641'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NurseGoods',
        ),
    ]
