# Generated by Django 2.2.7 on 2020-02-26 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0020_delete_nursegoods'),
    ]

    operations = [
        migrations.CreateModel(
            name='NurseGoods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_id', models.IntegerField(verbose_name='商品详情ID')),
                ('goods_name', models.CharField(default='', max_length=200, verbose_name='商品名称')),
                ('goods_price', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='商品价格')),
                ('goods_img', models.ImageField(blank=True, default='image/atom.png', null=True, upload_to='image/%Y/%m', verbose_name='商品图片')),
                ('goods_tip', models.DecimalField(decimal_places=1, default=0, max_digits=2, verbose_name='商品评分')),
                ('goods_sales', models.IntegerField(default=0, verbose_name='商品销量')),
                ('goods_brand', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='goods.Brand')),
            ],
            options={
                'verbose_name_plural': '护理用品',
                'verbose_name': '护理用品',
            },
        ),
    ]
