# Generated by Django 2.2.7 on 2020-02-26 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0021_nursegoods'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nursegoods',
            name='goods_brand',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='goods.Brand', verbose_name='商品品牌'),
        ),
    ]
