# Generated by Django 2.2.7 on 2020-02-26 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0022_auto_20200226_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='key_num',
            field=models.IntegerField(default=1, verbose_name='显示序号'),
        ),
    ]
