# Generated by Django 2.2.7 on 2020-02-27 09:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0023_brand_key_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='nursegoods',
            name='add_time',
            field=models.DateField(default=datetime.datetime.now, verbose_name='添加时间'),
        ),
    ]
