# Generated by Django 2.2.7 on 2020-02-27 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0024_nursegoods_add_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nursegoods',
            name='goods_name',
            field=models.CharField(default='', max_length=255, verbose_name='商品名称'),
        ),
    ]
