# Generated by Django 2.2.7 on 2020-02-28 22:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0025_auto_20200227_0937'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactLensBanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_id', models.IntegerField(verbose_name='商品详情ID')),
                ('goods_name', models.CharField(default='', max_length=255, verbose_name='商品名称')),
                ('goods_img', models.ImageField(blank=True, default='', null=True, upload_to='image/%Y/%m', verbose_name='商品图片')),
                ('add_time', models.DateField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '彩瞳 - 轮播图',
                'verbose_name_plural': '彩瞳 - 轮播图',
            },
        ),
        migrations.AlterModelOptions(
            name='brand',
            options={'verbose_name': '护理用品-品牌', 'verbose_name_plural': '护理用品-品牌'},
        ),
        migrations.AlterModelOptions(
            name='hotsell',
            options={'verbose_name': '护理用品-热销榜', 'verbose_name_plural': '护理用品-热销榜'},
        ),
        migrations.AlterModelOptions(
            name='nursegoods',
            options={'verbose_name': '护理用品-商品', 'verbose_name_plural': '护理用品-商品'},
        ),
        migrations.AlterField(
            model_name='hotsell',
            name='goods_id',
            field=models.IntegerField(verbose_name='商品ID'),
        ),
    ]
