# Generated by Django 2.2.7 on 2020-02-29 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0028_contactlensgoods'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assort',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_name', models.CharField(default='', max_length=100, verbose_name='商品分类')),
            ],
            options={
                'verbose_name': '商品分类',
                'verbose_name_plural': '商品分类',
            },
        ),
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_name', models.CharField(default='', max_length=100, verbose_name='商品属性名')),
                ('a_assort', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='goods.Assort', verbose_name='所属分类')),
            ],
            options={
                'verbose_name': '商品属性',
                'verbose_name_plural': '商品属性',
            },
        ),
        migrations.CreateModel(
            name='AttributeOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('o_name', models.CharField(default='', max_length=100, verbose_name='商品属性选项名')),
                ('o_attr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.Attribute', verbose_name='所属商品属性')),
            ],
            options={
                'verbose_name': '商品属性选项',
                'verbose_name_plural': '商品属性选项',
            },
        ),
        migrations.CreateModel(
            name='GoodsDetailBanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('g_big_img', models.ImageField(blank=True, default='', null=True, upload_to='image/%Y/%m', verbose_name='大图片')),
                ('g_small_img', models.ImageField(blank=True, default='', null=True, upload_to='image/%Y/%m', verbose_name='小图片')),
            ],
            options={
                'verbose_name': '商品详情-轮播图',
                'verbose_name_plural': '商品详情-轮播图',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(default='', max_length=255, verbose_name='产品名称')),
                ('p_assort', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='goods.Assort', verbose_name='所属分类')),
            ],
            options={
                'verbose_name': '产品单位SPU',
                'verbose_name_plural': '产品单位SPU',
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('s_id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='商品详情ID')),
                ('s_name', models.CharField(default='', max_length=255, verbose_name='商品名')),
                ('s_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.Product', verbose_name='所属产品')),
            ],
            options={
                'verbose_name': '库存量单位SKU',
                'verbose_name_plural': '库存量单位SKU',
            },
        ),
        migrations.CreateModel(
            name='StockAttrOp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_attr_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.Attribute', verbose_name='Attribute ID')),
                ('s_attr_op', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.AttributeOption', verbose_name='AttributeOption ID')),
                ('s_sku_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.Stock', verbose_name='SKU ID')),
            ],
            options={
                'verbose_name': 'SKU属性选项',
                'verbose_name_plural': 'SKU属性选项',
            },
        ),
        migrations.CreateModel(
            name='SkuBanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_goods_detail_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.GoodsDetailBanner', verbose_name='商品详情轮播图ID')),
                ('s_sku_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.Product', verbose_name='SKU ID')),
            ],
            options={
                'verbose_name': 'SKU轮播图',
                'verbose_name_plural': 'SKU轮播图',
            },
        ),
        migrations.AddField(
            model_name='goodsdetailbanner',
            name='s_spu_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.Product', verbose_name='SPU ID'),
        ),
        migrations.CreateModel(
            name='GoodsDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('g_img', models.ImageField(blank=True, default='', null=True, upload_to='image/%Y/%m', verbose_name='大图片')),
                ('g_spu_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.Product', verbose_name='SPU ID')),
            ],
            options={
                'verbose_name': '商品详情图片',
                'verbose_name_plural': '商品详情图片',
            },
        ),
    ]
