# Generated by Django 2.2.7 on 2020-02-29 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0029_auto_20200229_2124'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goodsdetail',
            old_name='g_spu_id',
            new_name='g_spu',
        ),
        migrations.RenameField(
            model_name='goodsdetailbanner',
            old_name='s_spu_id',
            new_name='s_spu',
        ),
        migrations.RenameField(
            model_name='skubanner',
            old_name='s_goods_detail_id',
            new_name='s_goods_detail',
        ),
        migrations.RenameField(
            model_name='skubanner',
            old_name='s_sku_id',
            new_name='s_sku',
        ),
        migrations.RenameField(
            model_name='stockattrop',
            old_name='s_attr_id',
            new_name='s_attr',
        ),
        migrations.RenameField(
            model_name='stockattrop',
            old_name='s_sku_id',
            new_name='s_sku',
        ),
    ]
