# Generated by Django 2.2.7 on 2020-03-01 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0030_auto_20200229_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skubanner',
            name='s_sku',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.Stock', verbose_name='SKU ID'),
        ),
    ]
