# Generated by Django 2.2.7 on 2020-03-02 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0032_stock_s_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d_content', models.CharField(default='', max_length=255, verbose_name='促销内容')),
            ],
            options={
                'verbose_name_plural': '促销内容',
                'verbose_name': '促销内容',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='p_brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='goods.Brand', verbose_name='品牌'),
        ),
        migrations.AddField(
            model_name='product',
            name='p_discount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='goods.Discount', verbose_name='促销信息'),
        ),
    ]
