# Generated by Django 2.2.7 on 2020-03-07 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0033_auto_20200302_1935'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discount',
            options={'verbose_name': '促销管理', 'verbose_name_plural': '促销管理'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='p_brand',
        ),
        migrations.AlterField(
            model_name='product',
            name='p_discount',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='goods.Discount', verbose_name='促销信息'),
        ),
    ]
