# Generated by Django 2.2.7 on 2020-03-07 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0034_auto_20200307_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='p_brand',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='goods.Brand', verbose_name='品牌'),
        ),
    ]
