# Generated by Django 2.2.7 on 2020-03-08 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0035_product_p_brand'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assort',
            options={'verbose_name': '分类管理', 'verbose_name_plural': '分类管理'},
        ),
        migrations.AlterModelOptions(
            name='attribute',
            options={'verbose_name': '属性管理', 'verbose_name_plural': '属性管理'},
        ),
        migrations.AlterModelOptions(
            name='attributeoption',
            options={'verbose_name': '属性选项管理', 'verbose_name_plural': '属性选项管理'},
        ),
        migrations.AlterModelOptions(
            name='brand',
            options={'verbose_name': '品牌管理', 'verbose_name_plural': '品牌管理'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'SPU管理', 'verbose_name_plural': 'SPU管理'},
        ),
        migrations.AlterModelOptions(
            name='stock',
            options={'verbose_name': 'SKU管理', 'verbose_name_plural': 'SKU管理'},
        ),
        migrations.AlterField(
            model_name='skubanner',
            name='s_goods_detail',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='goods.GoodsDetailBanner', verbose_name='商品详情轮播图ID'),
        ),
    ]
