# Generated by Django 2.2.7 on 2020-03-09 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0036_auto_20200308_2006'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='a_index',
            field=models.IntegerField(default=1, verbose_name='显示下标'),
        ),
    ]
