# Generated by Django 2.2.7 on 2020-02-24 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_emailverifyrecord'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailVerifyRecord',
        ),
    ]
